### ISSUE TITLE
Create a nested directory with all videos in the work plan

### ISSUE THREAD

**Issue by robperch** [robperch/tash_usmle#1]
- [x] Create list of tuples with all details about the videos
- [x] Create dataframe sorted and with the right column names
- [x] Save the resulting df as a csv file locally
